#!/usr/bin/env sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)

ENV_FILE="${DEMO_ENV_FILE:-$ROOT_DIR/.env}"
DEMO_LOAD_DOTENV="${DEMO_LOAD_DOTENV:-1}"

if [ "$DEMO_LOAD_DOTENV" = "1" ] && [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
fi

DEMO_DB_HOST="${DEMO_DB_HOST:-127.0.0.1}"
DEMO_DB_PORT="${DEMO_DB_PORT:-5433}"
DEMO_DB_NAME="${DEMO_DB_NAME:-netvrf}"
DEMO_DB_USER="${DEMO_DB_USER:-netvrf}"
DEMO_DB_PASSWORD="${DEMO_DB_PASSWORD:-netvrf}"
DEMO_REDIS_HOST="${DEMO_REDIS_HOST:-127.0.0.1}"
DEMO_REDIS_PORT="${DEMO_REDIS_PORT:-6380}"
DEMO_REDIS_DB="${DEMO_REDIS_DB:-0}"
DEMO_PROVIDER_HTTP_TIMEOUT_SECONDS="${DEMO_PROVIDER_HTTP_TIMEOUT_SECONDS:-15}"
DEMO_SEARCH_PROVIDER_TIMEOUT_SECONDS="${DEMO_SEARCH_PROVIDER_TIMEOUT_SECONDS:-15}"
DEMO_SYNC_PROVIDER_TIMEOUT_SECONDS="${DEMO_SYNC_PROVIDER_TIMEOUT_SECONDS:-120}"

DATABASE_URL="postgresql+psycopg://${DEMO_DB_USER}:${DEMO_DB_PASSWORD}@${DEMO_DB_HOST}:${DEMO_DB_PORT}/${DEMO_DB_NAME}"
REDIS_URL="redis://${DEMO_REDIS_HOST}:${DEMO_REDIS_PORT}/${DEMO_REDIS_DB}"

echo "Starting demo worker against isolated demo database and Redis."

exec env \
  APP_ENV=staging \
  APP_DEBUG=false \
  APP_RELOAD=false \
  HEALTH_REQUIRE_REDIS=true \
  DATABASE_URL="$DATABASE_URL" \
  REDIS_URL="$REDIS_URL" \
  PROVIDER_HTTP_TIMEOUT_SECONDS="$DEMO_PROVIDER_HTTP_TIMEOUT_SECONDS" \
  SEARCH_PROVIDER_TIMEOUT_SECONDS="$DEMO_SEARCH_PROVIDER_TIMEOUT_SECONDS" \
  SYNC_PROVIDER_TIMEOUT_SECONDS="$DEMO_SYNC_PROVIDER_TIMEOUT_SECONDS" \
  PYTHONUNBUFFERED=1 \
  /bin/sh "$ROOT_DIR/scripts/run_worker.sh"
